name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions  
on: 
  push:
    branches: 
      - main
jobs:
  Explore-Gitea-Actions:
    runs-on: debian
    # 发版时才会部署，正常提交不部署
    if: "contains(gitea.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm install
      - name: Build Project
        env: 
          CONTENT_REPO_TOKEN: ${{ secrets.CONTENT_REPO_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NUXT_JWT_SECRET: ${{ secrets.NUXT_JWT_SECRET }}
          NUXT_FEISHU_WEBHOOK: ${{ secrets.NUXT_FEISHU_WEBHOOK }}
          NUXT_FEISHU_USER_ID: ${{ secrets.NUXT_FEISHU_USER_ID }}
          NUXT_NODEMAILER_HOST: ${{ secrets.NUXT_NODEMAILER_HOST }}
          NUXT_NODEMAILER_PORT: ${{ secrets.NUXT_NODEMAILER_PORT }}
          NUXT_NODEMAILER_AUTH_USER: ${{ secrets.NUXT_NODEMAILER_AUTH_USER }}
          NUXT_NODEMAILER_AUTH_PASS: ${{ secrets.NUXT_NODEMAILER_AUTH_PASS }}
        run: NODE_OPTIONS="--max-old-space-size=4080" pnpm build
      - name: Copy and Build
        env: 
          CONTENT_REPO_TOKEN: ${{ secrets.CONTENT_REPO_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NUXT_FEISHU_WEBHOOK: ${{ secrets.NUXT_FEISHU_WEBHOOK }}
          NUXT_FEISHU_USER_ID: ${{ secrets.NUXT_FEISHU_USER_ID }}
          NUXT_JWT_SECRET: ${{ secrets.NUXT_JWT_SECRET }}
          NUXT_NODEMAILER_HOST: ${{ secrets.NUXT_NODEMAILER_HOST }}
          NUXT_NODEMAILER_PORT: ${{ secrets.NUXT_NODEMAILER_PORT }}
          NUXT_NODEMAILER_AUTH_USER: ${{ secrets.NUXT_NODEMAILER_AUTH_USER }}
          NUXT_NODEMAILER_AUTH_PASS: ${{ secrets.NUXT_NODEMAILER_AUTH_PASS }}
        run: |
          rm -rf /root/web/blog3/*
          mkdir -p /root/web/blog3/prisma
          cp -R .output/* /root/web/blog3/
          cp -R prisma/* /root/web/blog3/prisma/
          cp -R pm2.config.json /root/web/blog3/pm2.config.json
          cd /root/web/blog3
          prisma migrate deploy
          pm2 restart pm2.config.json --env production
      - run: echo "  The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo " ️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}          
      - run: echo "  This job's status is ${{ job.status }}."
      # 添加 webhook 通知步骤
      - name: Send Webhook Notification
        if: always()
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "msg_type": "text",
              "content": {
                "text": "${{ gitea.repository }} - release [${{job.status}}]"
              }
            }' \
            "${{ secrets.NUXT_FEISHU_WEBHOOK }}"